# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\build\ui\add_user.ui',
# licensing of 'src\build\ui\add_user.ui' applies.
#
# Created: Tue Aug  6 19:10:27 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AddUser(object):
    def setupUi(self, AddUser):
        AddUser.setObjectName("AddUser")
        AddUser.resize(516, 339)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddUser)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_logo = QtWidgets.QLabel(AddUser)
        self.label_logo.setMinimumSize(QtCore.QSize(80, 80))
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout.addWidget(self.label_logo)
        self.label_title = QtWidgets.QLabel(AddUser)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout.addWidget(self.label_title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(AddUser)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.input_login = QtWidgets.QLineEdit(AddUser)
        self.input_login.setObjectName("input_login")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_login)
        self.label_3 = QtWidgets.QLabel(AddUser)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(AddUser)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(AddUser)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.input_password = QtWidgets.QLineEdit(AddUser)
        self.input_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_password.setObjectName("input_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_password)
        self.input_confirm = QtWidgets.QLineEdit(AddUser)
        self.input_confirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_confirm.setObjectName("input_confirm")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.input_confirm)
        self.combo_type = QtWidgets.QComboBox(AddUser)
        self.combo_type.setObjectName("combo_type")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.combo_type)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.button_add_user = QtWidgets.QPushButton(AddUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add_user.sizePolicy().hasHeightForWidth())
        self.button_add_user.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_add_user.setFont(font)
        self.button_add_user.setDefault(True)
        self.button_add_user.setObjectName("button_add_user")
        self.horizontalLayout_2.addWidget(self.button_add_user)
        self.button_cancel = QtWidgets.QPushButton(AddUser)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_cancel.setFont(font)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout_2.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(AddUser)
        QtCore.QMetaObject.connectSlotsByName(AddUser)

    def retranslateUi(self, AddUser):
        self.label_title.setText(QtWidgets.QApplication.translate("AddUser", "Dodaj użytkownika", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("AddUser", "Login:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("AddUser", "Hasło:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("AddUser", "Powtórz hasło:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("AddUser", "Rodzaj konta:", None, -1))
        self.combo_type.setItemText(0, QtWidgets.QApplication.translate("AddUser", "Zwykłe", None, -1))
        self.combo_type.setItemText(1, QtWidgets.QApplication.translate("AddUser", "Administrator", None, -1))
        self.button_add_user.setText(QtWidgets.QApplication.translate("AddUser", "Dodaj", None, -1))
        self.button_cancel.setText(QtWidgets.QApplication.translate("AddUser", "Anuluj", None, -1))

