# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\build\ui\add_contractor.ui',
# licensing of 'src\build\ui\add_contractor.ui' applies.
#
# Created: Tue Aug  6 19:10:28 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_AddContractor(object):
    def setupUi(self, AddContractor):
        AddContractor.setObjectName("AddContractor")
        AddContractor.resize(500, 420)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddContractor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_logo = QtWidgets.QLabel(AddContractor)
        self.label_logo.setMinimumSize(QtCore.QSize(80, 80))
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout.addWidget(self.label_logo)
        self.label_2 = QtWidgets.QLabel(AddContractor)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(AddContractor)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.input_first_name = QtWidgets.QLineEdit(AddContractor)
        self.input_first_name.setObjectName("input_first_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_first_name)
        self.label_3 = QtWidgets.QLabel(AddContractor)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.input_last_name = QtWidgets.QLineEdit(AddContractor)
        self.input_last_name.setObjectName("input_last_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.input_last_name)
        self.label_4 = QtWidgets.QLabel(AddContractor)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.input_company = QtWidgets.QLineEdit(AddContractor)
        self.input_company.setObjectName("input_company")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.input_company)
        self.label_5 = QtWidgets.QLabel(AddContractor)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(AddContractor)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.input_nip = QtWidgets.QLineEdit(AddContractor)
        self.input_nip.setInputMask("")
        self.input_nip.setMaxLength(10)
        self.input_nip.setObjectName("input_nip")
        self.horizontalLayout_2.addWidget(self.input_nip)
        self.label_nip_valid = QtWidgets.QLabel(AddContractor)
        self.label_nip_valid.setMinimumSize(QtCore.QSize(21, 21))
        self.label_nip_valid.setMaximumSize(QtCore.QSize(21, 21))
        self.label_nip_valid.setText("")
        self.label_nip_valid.setScaledContents(True)
        self.label_nip_valid.setObjectName("label_nip_valid")
        self.horizontalLayout_2.addWidget(self.label_nip_valid)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 9)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_10 = QtWidgets.QLabel(AddContractor)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_regon = QtWidgets.QLineEdit(AddContractor)
        self.input_regon.setInputMask("")
        self.input_regon.setMaxLength(9)
        self.input_regon.setObjectName("input_regon")
        self.horizontalLayout_3.addWidget(self.input_regon)
        self.label_regon_valid = QtWidgets.QLabel(AddContractor)
        self.label_regon_valid.setMinimumSize(QtCore.QSize(21, 21))
        self.label_regon_valid.setMaximumSize(QtCore.QSize(21, 21))
        self.label_regon_valid.setText("")
        self.label_regon_valid.setObjectName("label_regon_valid")
        self.horizontalLayout_3.addWidget(self.label_regon_valid)
        self.horizontalLayout_3.setStretch(0, 8)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_13 = QtWidgets.QLabel(AddContractor)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.input_zip_1 = QtWidgets.QLineEdit(AddContractor)
        self.input_zip_1.setMaxLength(2)
        self.input_zip_1.setObjectName("input_zip_1")
        self.horizontalLayout_4.addWidget(self.input_zip_1)
        self.label_14 = QtWidgets.QLabel(AddContractor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.input_zip_2 = QtWidgets.QLineEdit(AddContractor)
        self.input_zip_2.setMaxLength(3)
        self.input_zip_2.setObjectName("input_zip_2")
        self.horizontalLayout_4.addWidget(self.input_zip_2)
        self.horizontalLayout_4.setStretch(0, 12)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 18)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_15 = QtWidgets.QLabel(AddContractor)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.input_city = QtWidgets.QLineEdit(AddContractor)
        self.input_city.setObjectName("input_city")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.input_city)
        self.label_16 = QtWidgets.QLabel(AddContractor)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.input_street = QtWidgets.QLineEdit(AddContractor)
        self.input_street.setObjectName("input_street")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.input_street)
        self.line = QtWidgets.QFrame(AddContractor)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.button_add = QtWidgets.QPushButton(AddContractor)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_add.setFont(font)
        self.button_add.setDefault(True)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout_5.addWidget(self.button_add)
        self.button_cancel = QtWidgets.QPushButton(AddContractor)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_cancel.setFont(font)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout_5.addWidget(self.button_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(AddContractor)
        QtCore.QMetaObject.connectSlotsByName(AddContractor)
        AddContractor.setTabOrder(self.input_first_name, self.input_last_name)
        AddContractor.setTabOrder(self.input_last_name, self.input_zip_1)
        AddContractor.setTabOrder(self.input_zip_1, self.input_zip_2)
        AddContractor.setTabOrder(self.input_zip_2, self.input_city)
        AddContractor.setTabOrder(self.input_city, self.input_street)
        AddContractor.setTabOrder(self.input_street, self.input_company)
        AddContractor.setTabOrder(self.input_company, self.input_nip)
        AddContractor.setTabOrder(self.input_nip, self.input_regon)
        AddContractor.setTabOrder(self.input_regon, self.button_add)
        AddContractor.setTabOrder(self.button_add, self.button_cancel)

    def retranslateUi(self, AddContractor):
        self.label_2.setText(QtWidgets.QApplication.translate("AddContractor", "Dodaj kontrahenta", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("AddContractor", "Imię:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("AddContractor", "Nazwisko:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("AddContractor", "Nazwa firmy:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("AddContractor", "NIP:", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("AddContractor", "<html><head/><body><p><span style=\" font-weight:600;\">PL</span></p></body></html>", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("AddContractor", "REGON:", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("AddContractor", "Kod pocztowy:", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("AddContractor", "—", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("AddContractor", "Miasto:", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("AddContractor", "Ulica i numer:", None, -1))
        self.button_add.setText(QtWidgets.QApplication.translate("AddContractor", "Dodaj", None, -1))
        self.button_cancel.setText(QtWidgets.QApplication.translate("AddContractor", "Anuluj", None, -1))

